fix: adjust `/* #__PURE__*/` comment timing
intlify/vue-i18n-next pull request #1623
Opened 2023-11-01 06:28 UTC by newives

2023-11-01 10:00 UTC, kazupon requested changes

2023-11-01 10:00 UTC, kazupon commented on packages/core-base/src/context.ts
> +export const setAdditionalMeta = (meta: MetaInfo | null): void => {
I think we swap to `/* #__NO_SIDE_EFFECTS__ */`, not remove `/* #__PURE__ */`
see the https://github.com/intlify/vue-i18n-next/issues/1599#issuecomment-1773776151
ref: https://github.com/javascript-compiler-hints/compiler-notations-spec/blob/main/no-side-effects-notation-spec.md

2023-11-01 10:02 UTC, kazupon commented on packages/core-base/src/compilation.ts
> +export const compileToFunction = <
same https://github.com/intlify/vue-i18n-next/pull/1623#pullrequestreview-1707899783

2023-11-01 10:03 UTC, kazupon requested changes

2023-11-01 10:03 UTC, kazupon commented on packages/core-base/src/context.ts
> +export const getAdditionalMeta = (): MetaInfo | null => _additionalMeta
same https://github.com/intlify/vue-i18n-next/pull/1623#pullrequestreview-1707899783

2023-11-01 11:05 UTC, newives commented
swap to `/* #__NO_SIDE_EFFECTS__ */`, not remove /* #__PURE__ */ Local test packaging will report the following error

<img width="1296" alt="图片" src="https://github.com/intlify/vue-i18n-next/assets/81661030/42a80afc-fbae-4c1d-82a2-e9ca27019b0c">

2023-11-01 11:23 UTC, newives commented
done

2023-11-02 03:17 UTC, kazupon approved these changes
Well done!
Thanks!

2023-11-02 03:31 UTC, merged