Documentation - t()
intlify/vue-i18n-next pull request #163
Opened 2020-10-28 13:49 UTC by michaelzangl

Currently, the .d.ts is stripped of all comments. There is already some documentation, so i included the comments and added some more.

One thing to note:
I removed the t(...args: unknown[]), since users should only see the typed versions of that method.

2020-10-28 15:25 UTC, kazupon requested changes

2020-10-28 15:25 UTC, kazupon commented on package.json
> +    "yarn": "^1.22.10"
please don't include to devDependencies. 🙏 
package manager should install globally your enviroment!

2020-10-28 15:27 UTC, kazupon commented
@michaelzangl 
vue-i18n-next API docs will be generated with `api-extractor`.
so, we need to be commented with the tsdocs style
https://api-extractor.com/pages/tsdoc/doc_comment_syntax/

2020-10-28 18:13 UTC, michaelzangl commented
@kazupon I cannot regenerate the documentation. When i run 'docs:api', it puts the documentation in `docs`, not in `docs/api`. What do you use to re-generate those files? Wouldn't it be better to not include them in the GIT and instead add them as build artifacts somewhere?

2020-10-30 08:38 UTC, kazupon commented
I've just re-setup docs enviroment.
you can run the commends:

- `yarn docs:setup`: build typescript codes and extract api markdown docs
- `yarn docs:dev`: run vitepress

2020-10-30 16:36 UTC, kazupon commented
I'll merge your PRs.
If you want to continue to update the document, please create a new one!
Thanks for your contribution!

2020-10-30 16:36 UTC, kazupon approved these changes

2020-10-30 16:36 UTC, merged