fix: not throw warnings when using implicit fallback
intlify/vue-i18n-next pull request #1798
Opened 2024-04-13 09:33 UTC by ShinnosukeKomiya

resolves https://github.com/intlify/vue-i18n-next/issues/1768

2024-04-13 11:06 UTC, kazupon requested changes
Thank you so much!
Great job!

I've just reviewed your PR, and added comment.
Please check it out.

2024-04-13 11:06 UTC, kazupon commented on packages/vue-i18n-core/test/issues.test.ts
I would also like to see additional tests for complex fallbacks using decision maps. 🙏 
https://vue-i18n.intlify.dev/guide/essentials/fallback.html#explicit-fallback-with-decision-maps

2024-04-14 11:49 UTC, ShinnosukeKomiya commented on packages/vue-i18n-core/test/issues.test.ts
Thank you for your review!
I have added tests for complex fallbacks using decision maps, so I hope you'll check it out 🙏

2024-04-14 12:06 UTC, kazupon approved these changes

2024-04-14 12:07 UTC, kazupon commented
@ShinnosukeKomiya 
Thank you!
I've just checked your test codes!
LGTM!

2024-04-14 12:07 UTC, merged