fix `hasOwnProperty is not a function`
intlify/vue-i18n-next pull request #306
Opened 2021-01-20 02:08 UTC by PeterAlfredLee

Fix #305

We should use function ` Object.prototype.hasOwnProperty.call` instead of function `hasOwnProperty` to check property.
Sorry for not consider enough before.

I notice there is a function [hasOwn](https://github.com/intlify/vue-i18n-next/blob/dcd005c238151b0924163b679992185755785af7/packages/vue-i18n/src/composer.ts#L973) in `packages/vue-i18n/src/composer.ts`.
This PR would like to move function `hasOwn` to `/packages/shared/src/index.ts` and replace all `hasOwnProperty` call with `hasOwn` call.

2021-01-20 05:51 UTC, kazupon requested changes
Thank you for your PR again!

in order to check to fix $305, Could you add test case ? 🙏

2021-01-21 02:07 UTC, PeterAlfredLee commented
Hi @kazupon, Just tested with this [repository](https://github.com/MartB/i18n-bug) that provided by issue #305 reporter,
and this PR will fix.

Issue #305 is caused by statement like this:
>import * as en from "./locales/en.json";

`en`  is a `Module` instead of a normal `Object` in this case.  So it will fail when we use `hasOwnProperty` call because `Module` don't have a `prototype` that point to `Object`.

I tried to add a test case but I failed.
Because in `test repository`(https://github.com/MartB/i18n-bug), the statement of `import * as en from "./locales/en.json";`  produce a `Module`, but in `vue-i18n-next` test file it produce a `Object`.

All in all, this PR can fix #305 (I have tested it), but I can't reproduce the problem when I try to add a test. WDTY ?

2021-01-21 02:44 UTC, kazupon commented
@PeterAlfredLee 
As commented in #294, I noticed that PR to be a braecking change.
https://github.com/intlify/vue-i18n-next/pull/294#issuecomment-764185615

vue-i18n-next is in RC phase right now, so I'll try to revert #294.

I think there are still a lot of things to consider to support #271.
I appreciate your contribution.

2021-01-21 03:03 UTC, PeterAlfredLee commented
> vue-i18n-next is in RC phase right now, so I'll try to revert #294.

@kazupon Sure, I understand and agree.

2021-01-21 03:27 UTC, kazupon commented
@PeterAlfredLee 
Thank you for your agreement.

In addition, We'll close also PR.
After v9 release, we’ll support #271 again.

2021-01-21 03:27 UTC, closed without merging